import type { ErrorCode } from './error-code';

export type HttpStatus =
  | 400
  | 401
  | 403
  | 404
  | 409
  | 413
  | 429
  | 500
  | 502
  | 503
  | 504;

export const ERROR_STATUS_BY_CODE = {
  INVALID_REQUEST: 400,
  PAYLOAD_TOO_LARGE: 413,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  USER_IDENTITY_REQUIRED: 401,
  INVALID_USER_IDENTITY: 401,
  IDENTITY_PROVIDER_UNAVAILABLE: 503,
  IDENTITY_JWKS_URL_UNSAFE: 400,
  IDENTITY_JWKS_SOURCE_UNAVAILABLE: 503,
  IDENTITY_JWKS_INVALID: 400,
  IDENTITY_CONFIG_CACHE_UNAVAILABLE: 503,
  FORBIDDEN: 403,
  ENVIRONMENT_NOT_ALLOWED: 403,
  IDEMPOTENCY_CONFLICT: 409,
  RATE_LIMITED: 429,
  AUTH_IDENTITY_UNAVAILABLE: 409,
  AUTH_VERIFICATION_TOKEN_INVALID: 400,
  AUTH_PASSWORD_RESET_TOKEN_INVALID: 400,
  AUTH_CREDENTIALS_INVALID: 401,
  AUTH_MFA_ALREADY_ENABLED: 409,
  AUTH_REFRESH_TOKEN_INVALID: 401,
  AUTH_USER_ACCESS_TOKEN_REQUIRED: 401,
  AUTH_USER_ACCESS_TOKEN_INVALID: 401,
  AUTH_WEB_SESSION_INVALID: 401,
  AUTH_WEB_SESSION_UNAVAILABLE: 503,
  ORGANIZATION_MEMBER_EXISTS: 409,
  ORGANIZATION_OWNER_REQUIRED: 409,
  ORGANIZATION_IDENTITY_ISSUER_CONFLICT: 409,
  ORGANIZATION_INVITE_TOKEN_INVALID: 400,
  ORGANIZATION_CREATION_LIMIT_REACHED: 409,
  AVATAR_CHANGED: 409,
  AVATAR_STORAGE_UNAVAILABLE: 503,
  SPEAKING_AUDIO_STORAGE_UNAVAILABLE: 503,
  CONCURRENCY_LIMIT: 429,
  QUOTA_EXCEEDED: 429,
  AI_SERVICE_THROTTLED: 503,
  AI_SERVICE_TIMEOUT: 504,
  AI_SERVICE_UNAVAILABLE: 503,
  AI_SERVICE_CONTRACT_VIOLATION: 502,
  AI_SERVICE_ERROR: 502,
  INTERNAL_ERROR: 500,
} as const satisfies Record<ErrorCode, HttpStatus>;

export function httpStatusForErrorCode(code: string): HttpStatus {
  // `Object.hasOwn`, not a plain index: a plain index reaches the prototype
  // chain, so `code = 'constructor'` would resolve to `Object` and escape as
  // a bogus status instead of refusing. The registry is looked up with error
  // codes that are a closed union today, but this function is the boundary
  // that says "unregistered code is a bug", and it must keep saying it.
  if (!Object.hasOwn(ERROR_STATUS_BY_CODE, code)) {
    throw new Error(`Unknown ErrorCode: ${code}`);
  }
  return ERROR_STATUS_BY_CODE[code as keyof typeof ERROR_STATUS_BY_CODE];
}
