import { ERROR_CODES, type ErrorCode } from './error-code';
import {
  ERROR_STATUS_BY_CODE,
  type HttpStatus,
  httpStatusForErrorCode,
} from './error-registry';

const EXPECTED_STATUSES = {
  INVALID_REQUEST: 400,
  PAYLOAD_TOO_LARGE: 413,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  USER_ASSERTION_REQUIRED: 401,
  INVALID_USER_ASSERTION: 401,
  IDENTITY_PROVIDER_UNAVAILABLE: 503,
  IDENTITY_CONFIG_CACHE_UNAVAILABLE: 503,
  FORBIDDEN: 403,
  ENVIRONMENT_NOT_ALLOWED: 403,
  IDEMPOTENCY_CONFLICT: 409,
  RATE_LIMITED: 429,
  AUTH_IDENTITY_UNAVAILABLE: 409,
  AUTH_VERIFICATION_TOKEN_INVALID: 400,
  AUTH_EMAIL_DELIVERY_UNAVAILABLE: 503,
  AUTH_CREDENTIALS_INVALID: 401,
  AUTH_REFRESH_TOKEN_INVALID: 401,
  AUTH_PASSWORD_RESET_TOKEN_INVALID: 400,
  AUTH_USER_ACCESS_TOKEN_REQUIRED: 401,
  AUTH_USER_ACCESS_TOKEN_INVALID: 401,
  ORGANIZATION_MEMBER_EXISTS: 409,
  ORGANIZATION_OWNER_REQUIRED: 409,
  ORGANIZATION_IDENTITY_ISSUER_CONFLICT: 409,
  ORGANIZATION_INVITE_TOKEN_INVALID: 400,
  ORGANIZATION_CREATION_LIMIT_REACHED: 409,
  CONCURRENCY_LIMIT: 429,
  QUOTA_EXCEEDED: 429,
  AI_SERVICE_THROTTLED: 503,
  AI_SERVICE_TIMEOUT: 504,
  AI_SERVICE_UNAVAILABLE: 503,
  AI_SERVICE_CONTRACT_VIOLATION: 502,
  AI_SERVICE_ERROR: 502,
  INTERNAL_ERROR: 500,
} as const satisfies Record<ErrorCode, HttpStatus>;

describe('error registry', () => {
  it('maps every public error code to its canonical HTTP status', () => {
    expect(Object.keys(ERROR_STATUS_BY_CODE).sort()).toEqual(
      [...ERROR_CODES].sort(),
    );

    for (const code of ERROR_CODES) {
      expect(httpStatusForErrorCode(code)).toBe(EXPECTED_STATUSES[code]);
    }
  });

  it('fails clearly for an unknown runtime code', () => {
    expect(() => httpStatusForErrorCode('UNKNOWN_CODE')).toThrow(
      'Unknown ErrorCode: UNKNOWN_CODE',
    );
  });
});
