export const ERROR_CODES = [
  'INVALID_REQUEST',
  'PAYLOAD_TOO_LARGE',
  'NOT_FOUND',
  'UNAUTHORIZED',
  'USER_ASSERTION_REQUIRED',
  'INVALID_USER_ASSERTION',
  'IDENTITY_PROVIDER_UNAVAILABLE',
  'FORBIDDEN',
  'ENVIRONMENT_NOT_ALLOWED',
  'IDEMPOTENCY_CONFLICT',
  'RATE_LIMITED',
  'CONCURRENCY_LIMIT',
  'QUOTA_EXCEEDED',
  'AI_SERVICE_THROTTLED',
  'AI_SERVICE_TIMEOUT',
  'AI_SERVICE_UNAVAILABLE',
  'AI_SERVICE_CONTRACT_VIOLATION',
  'AI_SERVICE_ERROR',
  'INTERNAL_ERROR',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
