
# 2. Backend API Gateway (Express -> Port 3020)

# 1. Frontend Web App (Next.js -> Port 3000)
server {
    server_name aihubproduction.com www.aihubproduction.com;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/aihubproduction.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/aihubproduction.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

# 2. Backend API Gateway (Express -> Port 3020)
server {
    server_name api.aihubproduction.com;
    server_tokens off;
    add_header Strict-Transport-Security "max-age=15552000" always;
      client_max_body_size 27m;

    location = /metrics {
        return 404;
    }

    location = /ready {
        return 404;
    }

    location / {
        proxy_pass http://127.0.0.1:3021;
        proxy_read_timeout 75s;
        proxy_send_timeout 75s;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/api.aihubproduction.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.aihubproduction.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = www.aihubproduction.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = aihubproduction.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name aihubproduction.com www.aihubproduction.com;
    return 404; # managed by Certbot




}

server {
    if ($host = aihub-api.aihubproduction.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name aihub-api.aihubproduction.com;
    return 404; # managed by Certbot


}

server {
    if ($host = api.aihubproduction.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name api.aihubproduction.com;
    server_tokens off;
    return 404; # managed by Certbot


}
